In [ ]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving emdat.xlsx to emdat (1).xlsx

In [ ]:
df = pd.read_excel('emdat.xlsx')

In [ ]:
df.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
0,1980-0002-MUS,Yes,nat-bio-epi-bac,Natural,Biological,Epidemic,Bacterial disease,NaN,Typhoid,MUS,...,NaN,NaN,NaN,NaN,NaN,26.270723,NaN,NaN,2003-07-01,2023-09-25
1,1980-0007-LBR,Yes,nat-bio-epi-bac,Natural,Biological,Epidemic,Bacterial disease,NaN,Cholera,LBR,...,NaN,NaN,NaN,NaN,NaN,26.270723,NaN,NaN,2003-07-01,2023-09-25
2,1980-0029-REU,Yes,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,Hyacinthe,REU,...,NaN,NaN,NaN,67000.0,255037.0,26.270723,NaN,NaN,2008-04-03,2023-09-25
3,1980-0040-MOZ,Yes,nat-bio-epi-bac,Natural,Biological,Epidemic,Bacterial disease,NaN,Cholera,MOZ,...,NaN,NaN,NaN,NaN,NaN,26.270723,NaN,NaN,2003-07-01,2023-09-25
4,1980-0043-TZA,Yes,nat-bio-epi-bac,Natural,Biological,Epidemic,Bacterial disease,NaN,Bubonic,TZA,...,NaN,NaN,NaN,NaN,NaN,26.270723,NaN,NaN,2003-07-01,2023-09-25

In [ ]:
df.shape

(3017, 47)

In [ ]:

df.columns.tolist()

['DisNo.',
 'Historic',
 'Classification Key',
 'Disaster Group',
 'Disaster Subgroup',
 'Disaster Type',
 'Disaster Subtype',
 'External IDs',
 'Event Name',
 'ISO',
 'Country',
 'Subregion',
 'Region',
 'Location',
 'Origin',
 'Associated Types',
 'OFDA/BHA Response',
 'Appeal',
 'Declaration',
 "AID Contribution ('000 US$)",
 'Magnitude',
 'Magnitude Scale',
 'Latitude',
 'Longitude',
 'River Basin',
 'Start Year',
 'Start Month',
 'Start Day',
 'End Year',
 'End Month',
 'End Day',
 'Total Deaths',
 'No. Injured',
 'No. Affected',
 'No. Homeless',
 'Total Affected',
 "Reconstruction Costs ('000 US$)",
 "Reconstruction Costs, Adjusted ('000 US$)",
 "Insured Damage ('000 US$)",
 "Insured Damage, Adjusted ('000 US$)",
 "Total Damage ('000 US$)",
 "Total Damage, Adjusted ('000 US$)",
 'CPI',
 'Admin Units',
 'GADM Admin Units',
 'Entry Date',
 'Last Update']

In [ ]:
df["Location"]

0                                              Widespread
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
                              ...
3012                   Kalyoubia, Shrkia, Fayoum province
3013    Boteti, Bobirwa, Mahalapye, Palapye, Selibe-Ph...
3014    Arrondissement du vent, Arrondissement sous le...
3015    Abim, Amudat, Kaabong, Kotido, Moroto, Nakapir...
3016    Ceel Barde, Rab Dhuure, Tayeeglow, Xudur distr...
Name: Location, Length: 3017, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 47 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   DisNo.                                     3017 non-null   object
 1   Historic                                   3017 non-null   object
 2   Classification Key                         3017 non-null   object
 3   Disaster Group                             3017 non-null   object
 4   Disaster Subgroup                          3017 non-null   object
 5   Disaster Type                              3017 non-null   object
 6   Disaster Subtype                           3017 non-null   object
 7   External IDs                               826 non-null    object
 8   Event Name                                 945 non-null    object
 9   ISO                                        3017 non-null   object
 10  Country                                    3017 non-null   object
 11  Subregion                                  3017 non-null   object
 12  Region                                     3017 non-null   object
 13  Location                                   2758 non-null   object
 14  Origin                                     1033 non-null   object
 15  Associated Types                           566 non-null    object
 16  OFDA/BHA Response                          3017 non-null   object
 17  Appeal                                     3017 non-null   object
 18  Declaration                                3017 non-null   object
 19  AID Contribution ('000 US$)                147 non-null    float64
 20  Magnitude                                  524 non-null    float64
 21  Magnitude Scale                            2274 non-null   object
 22  Latitude                                   288 non-null    float64
 23  Longitude                                  288 non-null    float64
 24  River Basin                                297 non-null    object
 25  Start Year                                 3017 non-null   int64
 26  Start Month                                2893 non-null   float64
 27  Start Day                                  1962 non-null   float64
 28  End Year                                   3017 non-null   int64
 29  End Month                                  2793 non-null   float64
 30  End Day                                    2044 non-null   float64
 31  Total Deaths                               2117 non-null   float64
 32  No. Injured                                610 non-null    float64
 33  No. Affected                               2168 non-null   float64
 34  No. Homeless                               424 non-null    float64
 35  Total Affected                             2653 non-null   float64
 36  Reconstruction Costs ('000 US$)            9 non-null      float64
 37  Reconstruction Costs, Adjusted ('000 US$)  9 non-null      float64
 38  Insured Damage ('000 US$)                  18 non-null     float64
 39  Insured Damage, Adjusted ('000 US$)        17 non-null     float64
 40  Total Damage ('000 US$)                    296 non-null    float64
 41  Total Damage, Adjusted ('000 US$)          292 non-null    float64
 42  CPI                                        2944 non-null   float64
 43  Admin Units                                1403 non-null   object
 44  GADM Admin Units                           1314 non-null   object
 45  Entry Date                                 3017 non-null   object
 46  Last Update                                3017 non-null   object
dtypes: float64(20), int64(2), object(25)
memory usage: 1.1+ MB

In [ ]:
df["ISO"].head()

0    MUS
1    LBR
2    REU
3    MOZ
4    TZA
Name: ISO, dtype: object

In [ ]:
columns_to_keep = ['Start Year', 'Disaster Type', 'Country', 'Total Affected', 'Total Deaths']

df_clean = df[columns_to_keep]
df_clean.shape

(3017, 5)

In [ ]:
df_clean.isnull().sum()

Start Year          0
Disaster Type       0
Country             0
Total Affected    364
Total Deaths      900
dtype: int64

In [ ]:
df_clean['Disaster Type'].value_counts()

Disaster Type
Flood                  1229
Epidemic                884
Storm                   326
Drought                 290
Mass movement (wet)      78
Infestation              72
Earthquake               56
Wildfire                 38
Extreme temperature      22
Volcanic activity        15
Mass movement (dry)       6
Animal incident           1
Name: count, dtype: int64

In [ ]:
climate_type = ['Flood', 'Storm', 'Drought', 'Wildfire', 'Extreme temperature']

df_climate = df_clean[df_clean['Disaster Type'].isin(climate_type)].copy()
df_climate.shape

(1905, 5)

In [ ]:
df_climate['Start Year'].value_counts().sort_index()

Start Year
1980     9
1981    14
1982    18
1983    22
1984    16
1985    15
1986     5
1987    13
1988    27
1989    21
1990    15
1991    19
1992     6
1993    17
1994    28
1995    28
1996    28
1997    29
1998    33
1999    53
2000    49
2001    55
2002    56
2003    56
2004    40
2005    51
2006    63
2007    83
2008    67
2009    63
2010    65
2011    65
2012    49
2013    44
2014    31
2015    52
2016    44
2017    45
2018    40
2019    77
2020    80
2021    55
2022    77
2023    58
2024    67
2025    57
Name: count, dtype: int64

In [ ]:
df_climate['Start Year'].min(), df_climate['Start Year'].max()

(1980, 2025)

Note: Raw data contains 1,883 climate disaster records after filtering. Downloaded from EM-DAT on April 16, 2026. Minor row differences from earlier analysis reflect live database updates.

In [ ]:
df_climate.isnull().sum()

Start Year          0
Disaster Type       0
Country             0
Total Affected    184
Total Deaths      735
dtype: int64

In [ ]:
# Step 4: Aggregate by year
yearly = df_climate.groupby(['Start Year', 'Disaster Type']).agg(
    Events=('Disaster Type', 'count'),
    Total_Affected=('Total Affected', 'sum'),
    Total_Deaths=('Total Deaths', 'sum')
).reset_index()

yearly.head(10)

   Start Year Disaster Type  Events  Total_Affected  Total_Deaths
0        1980       Drought       8       8495000.0           0.0
1        1980         Storm       1          7000.0          25.0
2        1981       Drought       5       7330000.0      103000.0
3        1981         Flood       7        657235.0         177.0
4        1981         Storm       2        119850.0         107.0
5        1982       Drought       8       2237300.0           0.0
6        1982         Flood       6        667514.0         229.0
7        1982         Storm       4        104722.0          95.0
8        1983       Drought      15      34423000.0      450500.0
9        1983         Flood       3        137000.0           0.0

In [ ]:
yearly.shape

(177, 5)

In [ ]:
yearly['Disaster Type'].value_counts()

Disaster Type
Drought                46
Storm                  45
Flood                  45
Wildfire               25
Extreme temperature    16
Name: count, dtype: int64

In [ ]:
yearly['Total Affected'] = yearly['Total_Affected'].fillna(0).astype(int)
yearly['Total Deaths'] = yearly['Total_Deaths'].fillna(0).astype(int)
yearly.drop(columns=['Total_Affected', 'Total_Deaths'], inplace=True)
yearly.head()

   Start Year Disaster Type  Events  Total Affected  Total Deaths
0        1980       Drought       8         8495000             0
1        1980         Storm       1            7000            25
2        1981       Drought       5         7330000        103000
3        1981         Flood       7          657235           177
4        1981         Storm       2          119850           107

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
yearly.to_csv('africa_climate_timeline.csv', index=False)

In [ ]:
# Step 6: Pivot to wide format
yearly_wide = yearly.pivot(index='Start Year',
                           columns='Disaster Type',
                           values='Events').fillna(0).astype(int).reset_index()

yearly_wide.head()

Disaster Type,Start Year,Drought,Extreme temperature,Flood,Storm,Wildfire
0,1980,8,0,0,1,0
1,1981,5,0,7,2,0
2,1982,8,0,6,4,0
3,1983,15,0,3,4,0
4,1984,4,0,3,8,1

In [ ]:
yearly_wide.to_csv('/content/drive/MyDrive/africa_climate_wide.csv', index=False)

In [ ]:
df_climate['Decade'] = (df_climate["Start Year"] // 10) * 10

df_climate[["Start Year", "Decade"]].head(10)

    Start Year  Decade
2         1980    1980
8         1980    1980
9         1980    1980
10        1980    1980
11        1983    1980
12        1980    1980
13        1983    1980
14        1982    1980
15        1983    1980
16        1981    1980

In [ ]:
df_climate.groupby(['Decade', 'Disaster Type']).agg(Event_count=('Disaster Type', 'count'))

                            Event_count
Decade Disaster Type
1980   Drought                       59
       Flood                         64
       Storm                         35
       Wildfire                       2
1990   Drought                       53
       Extreme temperature            5
       Flood                        152
       Storm                         38
       Wildfire                       8
2000   Drought                       70
       Extreme temperature            6
       Flood                        404
       Storm                         89
       Wildfire                      14
2010   Drought                       66
       Extreme temperature           10
       Flood                        349
       Storm                         80
       Wildfire                       7
2020   Drought                       42
       Extreme temperature            1
       Flood                        260
       Storm                         84
       Wildfire                       7

In [ ]:
decade_summary = df_climate.groupby(['Decade', 'Disaster Type']).agg(
    Event_count=('Disaster Type', 'count'),
).reset_index()

decade_summary

    Decade        Disaster Type  Event_count
0     1980              Drought           59
1     1980                Flood           64
2     1980                Storm           35
3     1980             Wildfire            2
4     1990              Drought           53
5     1990  Extreme temperature            5
6     1990                Flood          152
7     1990                Storm           38
8     1990             Wildfire            8
9     2000              Drought           70
10    2000  Extreme temperature            6
11    2000                Flood          404
12    2000                Storm           89
13    2000             Wildfire           14
14    2010              Drought           66
15    2010  Extreme temperature           10
16    2010                Flood          349
17    2010                Storm           80
18    2010             Wildfire            7
19    2020              Drought           42
20    2020  Extreme temperature            1
21    2020                Flood          260
22    2020                Storm           84
23    2020             Wildfire            7

In [ ]:
Decade_wide = decade_summary.pivot(index= 'Decade',
                                   columns = 'Disaster Type',
                                   values= 'Event_count').fillna(0).astype(int).reset_index()

Decade_wide

Disaster Type  Decade  Drought  Extreme temperature  Flood  Storm  Wildfire
0                1980       59                    0     64     35         2
1                1990       53                    5    152     38         8
2                2000       70                    6    404     89        14
3                2010       66                   10    349     80         7
4                2020       42                    1    260     84         7

In [ ]:
Decade_wide.to_csv('/content/drive/MyDrive/africa_flood_dominance.csv', index=False)